---
title: "cprob_plot_example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{cprob_plot_example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, eval=FALSE}
# knitr::opts_chunk$set(
#   collapse = TRUE,
#   comment = "#>"
# )
rmarkdown::render(input = "cprob_plot_example.Rmd", envir = parent.frame())
```

# Import example datasets (or your own dataset)
```{r}
data <- gutbehaviour::ABX_2
average.velocity <- gutbehaviour::ABX_2_avg_velocity
```

# Preprocess dataset
```{r}
PDATA <- gutbehaviour::lm_preprocess(data, average.velocity)
```

# Generate event profile 
```{r}
eventprf <- gutbehaviour::EventProfiles2(PDATA, 10, 3, factor.freeze = 0.05, factor.flight = 2)
```
## combined plots
```{r}
result <- gutbehaviour::cumuprob_plot(eventprf, PDATA$time_intervals)
result$plot # cdf plot
eventprf <- gutbehaviour::processed_eventprofiles(eventprf)
combined_plot <- gutbehaviour::combinedplot(data, average.velocity, eventprf)
combined_plot # combined raster 
raster <- gutbehaviour::various_lm_plots(eventprf, time_intervals = PDATA$time_intervals)
raster
```





