---
title: "Cumulative Time"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Cumulative Time}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(gutbehaviour)
```

```{r}
library(tidyverse)
data <- gutbehaviour::ABX_2 # data matrix here
average.velocity <- gutbehaviour::ABX_2_avg_velocity # average velocity here 
P.DATA <- gutbehaviour::lm_preprocess(data, average.velocity)
```

```{r}
event_profiles <- gutbehaviour::EventProfiles_all(P.DATA, 10, 3, factor.freeze = 0.05, factor.flight = 2)
```

```{r}
event.prof <- event_profiles[[1]] %>% gutbehaviour::processed_eventprofiles()
```

```{r}
event_concerned = "freeze"
all_subjects = P.DATA$subject_names
time_intervals <- P.DATA$time_intervals
final_time_limit <- gsub("(.*)-","",time_intervals[length(time_intervals)]) %>% as.POSIXct(format = "%H:%M:%OS")
default_time_seq <- seq.POSIXt(from = as.POSIXct("00:00:00",format = "%H:%M:%OS"), to = final_time_limit, by=0.001) # in miliseconds
total_time <- sapply(default_time_seq, function(x){accumulate_time(x, considerata)})

CONSIDERATA_SUBT <- lapply(all_subjects, function(x){get_relevant_profile(event.prof, x, "shelter")})
CUMU_FREEZE_TIME_SUBT <- lapply(CONSIDERATA_SUBT, function(x){sapply(default_time_seq, function(y){accumulate_time(y, x)})})
cumu_freeze_time_subt <- do.call(cbind, CUMU_FREEZE_TIME_SUBT) %>% as.data.frame()
colnames(cumu_freeze_time_subt) <- all_subjects
cumu_freeze_time_subt$time <- default_time_seq
cumu_freeze_time_subt_to_plot <- gather(cumu_freeze_time_subt, key = "subjects", value = "cumulative time (in s)", 1:12)
freeze_cumu_time <- ggplot(cumu_freeze_time_subt_to_plot, aes(x=time, y=cumu_freeze_time_subt_to_plot$`cumulative time (in s)`/150,color = subjects)) + geom_line() + theme_classic()
```

```{r}
get_relevant_profile <- function(event.prof, subject_concerned, event_concerned){
  considerata <- filter(event.prof, subject == subject_concerned) %>% filter(event == event_concerned)
  return(considerata)
}
```


```{r}
accumulate_time <- function(time_considered, considerata){
  accumu_time <- time_considered - considerata$start
  accumu_time <- accumu_time[accumu_time >= 0]
  return(sum(accumu_time))
}
```
