---
title: "Standard Pipeline"
author: "Hephaes"
date: "2023-06-18"
output:
  html_document: default
  pdf_document: default
---

# Removing old package and installing the new one
```{r, cache = TRUE, results='hide', message=FALSE, warning=FALSE}
remove.packages("gutbehaviour")
library(tidyverse)
library(devtools)
devtools::install_github("ocinei/gutbehaviour")
```

# Data imports and preprocessing 
```{r}
library(devtools)
library(tidyverse)
data <- all_mice # data matrix here
colnames(data) <- c("time",seq_len(121))
average.velocity <- all_mice_velocity # average velocity here 
P.DATA <- gutbehaviour::lm_preprocess(data, average.velocity)
```

# Standard pipeline
```{r}
event_profiles <- gutbehaviour::EventProfiles_all(P.DATA, 14, 2, factor.freeze = 0.2, factor.flight = 3)
```

```{r}
eventless_profile <- gutbehaviour::.EventlessProfile(event_profiles, P.DATA)
```

```{r}
processed_event_prof <- rbind(event_profiles[[1]], eventless_profile) %>% gutbehaviour::processed_eventprofiles()
```

# Plotting 
```{r}
cumuprob_plot_new <- gutbehaviour::cumuprob_plot(event_profiles[[1]], P.DATA$time_intervals)
```

```{r}
raster <- gutbehaviour::various_lm_plots(processed_event_prof,time_intervals = P.DATA$time_intervals, size_parameter = 1.5)
```

```{r}
cumuprob_plot_new$plot
```

```{r}
raster
```
```{r}
raster <- gutbehaviour::various_lm_plots(processed_event_prof,time_intervals = P.DATA$time_intervals, size_parameter = 1.5)
raster_rearranged <- raster + scale_y_discrete(limits = factor(seq_len(121)))
raster_rearranged <- raster_rearranged + theme(
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  plot.background = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.border = element_blank(),
  axis.title.y.left = element_blank())
```

```{r}
png(file="new_raster.png",
width=1000, height=1000)
raster_rearranged
dev.off()
```



