#' Processing event profiles generated from EventProfiles function for easier plotting
#'
#' @param Eventprofiles the event profile generated by EventProfiles function. See documentation for EventProfiles for details.
#' @export
#' @return a data frame that contains only the complete cases (Eventprofiles without the NA) and formatting time
processed_eventprofiles <- function(Eventprofiles){

  Eventprofiles1 <- Eventprofiles[complete.cases(Eventprofiles),]
  Eventprofiles1$start <- sapply(Eventprofiles1$start, function(x) gsub("-(.*)","",x))
  Eventprofiles1$end <- sapply(Eventprofiles1$end, function(x) gsub("(.*)-","",x))
  Eventprofiles1$start <- as.POSIXct(Eventprofiles1$start, "Asia/Taipei", format="%H:%M:%OS")
  Eventprofiles1$end <- as.POSIXct(Eventprofiles1$end, "Asia/Taipei", format="%H:%M:%OS")

  return(Eventprofiles1)
}
