#' Produce different types of plots for lm experiments
#'
#' @param event_profiles The event profile generated by EventProfiles function AND updated by processed_eventprofiles function
#' @param time a vector containing the times at which stimulus was given in the experiment; default is 0; the formats must be the same as the components of time_intervals vector (see the time_intervals argument below)
#' @param size_parameter a positive integer for setting the size of each event segment; the larger the integer the larger the segment
#' @param time_intervals the time interval vector in the processed data output by lm_preprocess
#'
#' @return a list of relevant plots, currenlt showing the raster plot first
#' @export
various_lm_plots <- function(event_profiles, time = 0, size_parameter = 10, time_intervals, time_axis_reverse = FALSE) {

  # getting the limits of time_intervals
  initial_time_limit = gsub("-(.*)","",time_intervals[1])
  final_time_limit = gsub("(.*)-","",time_intervals[length(time_intervals)])

  # raster plot
  if (!is.numeric(time)) {
    time <- as.POSIXct(time,"Asia/Taipei", format="%H:%M:%OS")
    gp <- ggplot(event_profiles, aes(color = event)) +
      geom_segment(aes(x = start, xend = end , y = subject, yend = subject), size = size_parameter) +
      scale_x_datetime(breaks = ("1 sec"), labels = scales::date_format("%S"), limits = as.POSIXct(c(initial_time_limit,final_time_limit), format = "%H:%M:%OS")) + xlab("time (in seconds)") + theme_light() + geom_vline(xintercept = time, color="blue", linetype="dashed", size = 1) + scale_colour_manual(values = c("#A9A9A9","#E26860","#53B0B5","#F5D584"))
  } else {
    gp <- ggplot(event_profiles, aes(color = event)) +
      geom_segment(aes(x = start, xend = end , y = subject, yend = subject), size = size_parameter) +
      scale_x_datetime(breaks = ("1 sec"), labels = scales::date_format("%S"), limits = as.POSIXct(c(initial_time_limit,final_time_limit), format = "%H:%M:%OS")) + xlab("time (in seconds)") + theme_light() + scale_colour_manual(values = c("#A9A9A9","#E26860","#53B0B5","#F5D584"))
  }
  if (time_axis_reverse == TRUE) {
    gp <- gp + coord_x_datetime(xlim = as.POSIXct(c(final_time_limit, initial_time_limit), format = "%H:%M:%OS"))
  }
  return(gp)
}

