#' Produce different types of plots for lm experiments
#'
#' @param Eventprofiles The event profile generated by EventProfiles function AND updated by processed_eventprofiles function
#' @param time a vector containing the times at which stimulus was given in the experiment; default is 0.
#'
#' @return a list of relevant plots
#' @export
various_lm_plots <- function(Eventprofiles, time = 0) {
  # raster plot
  time <- time <- as.POSIXct(time,"Asia/Taipei", format="%H:%M:%OS")
  gp <- ggplot(event_profiles, aes(color = event)) +
    geom_segment(aes(x = start, xend = end , y = subject, yend = subject), size = 6) +
    scale_x_datetime(breaks = ("1 sec"), labels = scales::date_format("%S")) + xlab("time (in seconds)") + theme_classic() + geom_vline(xintercept = time, color="blue", linetype="dashed", size = 1)
  return(gp)
}
